import { describe, it, expect } from "bun:test";
import { generateApiUtilsCode } from "../../../src/api/code_generation";
import type { APIEndpointEntry } from "../../../src/api/types";
import * as v from "valibot";
import { Path } from "../../../src/core/fs";

// Helper to create mock entries
function createEntry(
  method: string,
  route: string,
  filePath: string,
  input: any = v.null(),
  output: any = v.null(),
): APIEndpointEntry<any, any> {
  return {
    method: method as any,
    route,
    input,
    output,
    file: Path.resolve(filePath),
  };
}

describe("generateApiUtilsCode", () => {
  describe("basic functionality", () => {
    it("should generate code with empty entries", () => {
      const code = generateApiUtilsCode([]);

      expect(code).toBe(`// Auto-generated by noxt
import { ApiRouter as NoxtApiRouter, getApiHandlers } from "noxt/runtime";
import type { InferDefinitions } from "noxt/api";


const apiRoutesData = {
  
} as const;
const handlers = getApiHandlers(apiRoutesData, "");

type ApiRoutes = InferDefinitions<typeof apiRoutesData>;

export { type ApiRoutes, handlers };
`);
    });

    it("should generate code with single entry", () => {
      const apiTestEntry = createEntry("GET", "/api/test", "api/test.ts");
      const entries = [apiTestEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_test_GET } from " +
          JSON.stringify(apiTestEntry.file.absolute),
      );
      expect(code).toContain(
        '{\n  \"/api/test\": {\n    \"GET\": _api_test_GET\n  }\n}',
      );
    });

    it("should generate code with multiple entries from same file", () => {
      const getApiTestEntry = createEntry("GET", "/api/test", "api/test.ts");
      const postApiTestEntry = createEntry("POST", "/api/test", "api/test.ts");
      const entries = [getApiTestEntry, postApiTestEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_test_GET, POST as _api_test_POST } from " +
          JSON.stringify(getApiTestEntry.file.absolute),
      );
      expect(code).toContain(`{
  \"/api/test\": {
    \"GET\": _api_test_GET,
    \"POST\": _api_test_POST
  }
}`);
    });

    it("should generate code with multiple entries from different files", () => {
      const getApiUsersEntry = createEntry("GET", "/api/users", "api/users.ts");
      const postApiPostsEntry = createEntry(
        "POST",
        "/api/posts",
        "api/posts.ts",
      );
      const entries = [getApiUsersEntry, postApiPostsEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_users_GET } from " +
          JSON.stringify(getApiUsersEntry.file.absolute),
      );
      expect(code).toContain(
        "import { POST as _api_posts_POST } from " +
          JSON.stringify(postApiPostsEntry.file.absolute),
      );
      expect(code).toContain(`{
  \"/api/users\": {
    \"GET\": _api_users_GET
  },
  \"/api/posts\": {
    \"POST\": _api_posts_POST
  }
}`);
    });

    it("should handle routes with slashes", () => {
      const getApiUsersEntry = createEntry(
        "GET",
        "/api/v1/users",
        "./src/api/v1/users.ts",
      );
      const entries = [getApiUsersEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_v1_users_GET } from " +
          JSON.stringify(getApiUsersEntry.file.absolute),
      );
      expect(code).toContain('"GET": _api_v1_users_GET');
    });
  });

  describe("export statements", () => {
    it("should include router and ApiRouter exports", () => {
      const entries = [createEntry("GET", "/api/test", "./src/api/test.ts")];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain("export { type ApiRoutes, handlers };");
    });
  });

  describe("edge cases", () => {
    it("should handle route with special characters in path", () => {
      const entryWithDash = createEntry(
        "GET",
        "/api/test-route",
        "./src/api/test-route.ts",
      );
      const entries = [entryWithDash];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_test_route_GET } from " +
          JSON.stringify(entryWithDash.file.absolute),
      );
      expect(code).toContain('"GET": _api_test_route_GET');
    });

    it("should handle multiple HTTP methods", () => {
      const entries = [
        createEntry("GET", "/api/test", "./src/api/test.ts"),
        createEntry("POST", "/api/test", "./src/api/test.ts"),
        createEntry("PUT", "/api/test", "./src/api/test.ts"),
        createEntry("DELETE", "/api/test", "./src/api/test.ts"),
        createEntry("PATCH", "/api/test", "./src/api/test.ts"),
      ];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain("GET as _api_test_GET");
      expect(code).toContain("POST as _api_test_POST");
      expect(code).toContain("PUT as _api_test_PUT");
      expect(code).toContain("DELETE as _api_test_DELETE");
      expect(code).toContain("PATCH as _api_test_PATCH");
    });

    it("should handle entries with different route structures", () => {
      const apiEntry = createEntry("GET", "/api", "./api/index.ts");
      const apiUsersEntry = createEntry(
        "GET",
        "/api/users",
        "./src/api/users.ts",
      );
      const nestedEntry = createEntry(
        "PUT",
        "/api/users/create",
        "./api/users/create.ts",
      );

      const entries = [apiEntry, apiUsersEntry, nestedEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        "import { GET as _api_GET } from " +
          JSON.stringify(apiEntry.file.absolute),
      );
      expect(code).toContain(
        "import { GET as _api_users_GET } from " +
          JSON.stringify(apiUsersEntry.file.absolute),
      );
      expect(code).toContain(
        "import { PUT as _api_users_create_PUT } from " +
          JSON.stringify(nestedEntry.file.absolute),
      );
    });
  });
});
