import { describe, it, expect, beforeAll, afterAll, mock } from "bun:test";
import { generateApiUtilsCode } from "../../../src/api/code_generation";
import type { APIEndpointEntry } from "../../../src/api/build";
import * as v from "valibot";
import { Path } from "../../../src/core/fs";
import { writeFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";

// Helper to create mock entries
function createEntry(
  method: string,
  route: string,
  filePath: string,
  input: any = v.null(),
  output: any = v.null(),
): APIEndpointEntry<any, any> {
  return {
    method: method as any,
    route,
    input,
    output,
    file: Path.resolve(filePath),
  };
}

describe("generateApiUtilsCode", () => {
  describe("basic functionality", () => {
    it("should generate code with empty entries", () => {
      const code = generateApiUtilsCode([]);

      expect(code).toBe(`// Auto-generated by noxt
import { InferInput, InferOutput } from "valibot";


const apiRoutesData = {

};
type ApiRouter = typeof apiRoutesData;

const BASE = "";
  
function api<TEndpoint extends keyof ApiRouter>(
  endpoint: TEndpoint,
): (
  input: v.InferOutput<ApiRouter[TEndpoint]['input']>,
) => Promise<v.InferInput<ApiRouter[TEndpoint]['output']>> {
  return async (input) => {
    let [method, url] = endpoint.split(' ', 2);
    url = BASE + url;
    const response = await fetch(url, { method });
    const data = await response.json();
    return data as v.InferInput<ApiRouter[TEndpoint]['output']>;
  };
}

export { api, type ApiRouter };
`);
    });

    it("should generate code with single entry", () => {
      const apiTestEntry = createEntry("GET", "/api/test", "api/test.ts");
      const entries = [apiTestEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_test_GET } from "' +
          apiTestEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain('"GET /api/test": _api_test_GET');
    });

    it("should generate code with multiple entries from same file", () => {
      const getApiTestEntry = createEntry("GET", "/api/test", "api/test.ts");
      const postApiTestEntry = createEntry("POST", "/api/test", "api/test.ts");
      const entries = [getApiTestEntry, postApiTestEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_test_GET, POST as _api_test_POST } from "' +
          getApiTestEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain('"GET /api/test": _api_test_GET');
      expect(code).toContain('"POST /api/test": _api_test_POST');
    });

    it("should generate code with multiple entries from different files", () => {
      const getApiUsersEntry = createEntry("GET", "/api/users", "api/users.ts");
      const postApiPostsEntry = createEntry(
        "POST",
        "/api/posts",
        "api/posts.ts",
      );
      const entries = [getApiUsersEntry, postApiPostsEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_users_GET } from "' +
          getApiUsersEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain(
        'import { POST as _api_posts_POST } from "' +
          postApiPostsEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain('"GET /api/users": _api_users_GET');
      expect(code).toContain('"POST /api/posts": _api_posts_POST');
    });

    it("should handle routes with slashes", () => {
      const getApiUsersEntry = createEntry(
        "GET",
        "/api/v1/users",
        "./src/api/v1/users.ts",
      );
      const entries = [getApiUsersEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_v1_users_GET } from "' +
          getApiUsersEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain('"GET /api/v1/users": _api_v1_users_GET');
    });

    it("should handle base URL parameter", () => {
      const entries = [createEntry("GET", "/api/test", "./src/api/test.ts")];

      const code = generateApiUtilsCode(entries, "http://localhost:3000");

      expect(code).toContain('const BASE = "http://localhost:3000";');
    });

    it("should handle empty base URL parameter", () => {
      const entries = [createEntry("GET", "/api/test", "./src/api/test.ts")];

      const code = generateApiUtilsCode(entries, "");

      expect(code).toContain('const BASE = "";');
    });

    it("should handle undefined base URL parameter", () => {
      const entries = [createEntry("GET", "/api/test", "./src/api/test.ts")];

      const code = generateApiUtilsCode(entries, undefined);

      expect(code).toContain('const BASE = "";');
    });
  });

  describe("export statements", () => {
    it("should include api and ApiRouter exports", () => {
      const entries = [createEntry("GET", "/api/test", "./src/api/test.ts")];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain("export { api, type ApiRouter };");
    });
  });

  describe("runtime execution tests", () => {
    const CACHE_DIR = path.resolve(".cache-test-api-execution");
    let counter = 0;

    async function generateAndLoadApiCode(
      entries: APIEndpointEntry<any, any>[],
      base?: string,
    ) {
      const code = generateApiUtilsCode(entries, base);
      const fileName = `api_utils.${counter++}.ts`;
      const filePath = path.resolve(CACHE_DIR, fileName);
      await mkdir(CACHE_DIR, { recursive: true });
      await writeFile(filePath, code);
      return import(filePath);
    }

    async function writeEntry(method: string, route: string, code: string) {
      const mockEndpointPath = path.resolve(
        CACHE_DIR,
        `mock_endpoint.${counter++}.ts`,
      );
      await writeFile(mockEndpointPath, code);
      return createEntry(method, route, mockEndpointPath);
    }

    beforeAll(async () => {
      await rm(CACHE_DIR, { recursive: true, force: true });
      await mkdir(CACHE_DIR, { recursive: true });
    });

    afterAll(async () => {
      await rm(CACHE_DIR, { recursive: true, force: true });
    });

    it("should export api function", async () => {
      const mockEntries = [
        await writeEntry(
          "GET",
          "/api/test",
          `
          import * as v from "valibot";
          export const GET = {
            input: v.object({}),
            output: v.object({}),
          };
          `,
        ),
      ];

      const mod = await generateAndLoadApiCode(mockEntries);
      expect(mod.api).toBeDefined();
      expect(typeof mod.api).toBe("function");
    });

    it("should handle base URL correctly", async () => {
      const mockEntries = [
        await writeEntry(
          "GET",
          "/api/test",
          `
          import * as v from "valibot";
          export const GET = {
            input: v.object({ name: v.string() }),
            output: v.object({ greeting: v.string() }),
          };
          `,
        ),
      ];

      const mockFetch = mock();
      // @ts-ignore
      global.fetch = mockFetch;

      mockFetch.mockImplementation(
        async (url: string, options?: RequestInit) => {
          const urlUrl = new URL(url);
          const result = new Response(
            `{"greeting":"Hello ${urlUrl.searchParams.get("name") ?? "World"}!"}`,
            { status: 200 },
          );
          return result;
        },
      );

      const mod = await generateAndLoadApiCode(
        mockEntries,
        "http://localhost:3000",
      );
      const testApi = mod.api("GET /api/test");
      const result = await testApi({ name: "Tom" });

      expect(mod.api).toBeDefined();
      expect(result).toBe({ greeting: "Hello Tom!" });

      mockFetch.mockReset();
    });

    it("should generate correct endpoint keys", async () => {
      // Create mock endpoint modules in cache dir
      const mockUsersEndpointCode = `
        import * as v from "valibot";
        export const GET = {
          input: v.object({}),
          output: v.object({}),
        };
      `;
      const mockPostsEndpointCode = `
        import * as v from "valibot";
        export const POST = {
          input: v.object({}),
          output: v.object({}),
        };
      `;

      const mockUsersPath = path.join(CACHE_DIR, "mock_users.ts");
      const mockPostsPath = path.join(CACHE_DIR, "mock_posts.ts");
      await writeFile(mockUsersPath, mockUsersEndpointCode);
      await writeFile(mockPostsPath, mockPostsEndpointCode);

      // Use absolute paths for the mock endpoints
      const mockEntries = [
        createEntry("GET", "/api/users", mockUsersPath),
        createEntry("POST", "/api/posts", mockPostsPath),
      ];

      const mod = await generateAndLoadApiCode(mockEntries);
      expect(mod.api).toBeDefined();
    });
  });

  describe("edge cases", () => {
    it("should handle route with special characters in path", () => {
      const entryWithDash = createEntry(
        "GET",
        "/api/test-route",
        "./src/api/test-route.ts",
      );
      const entries = [entryWithDash];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_test-route_GET } from "' +
          entryWithDash.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain('"GET /api/test-route": _api_test-route_GET');
    });

    it("should handle multiple HTTP methods", () => {
      const entries = [
        createEntry("GET", "/api/test", "./src/api/test.ts"),
        createEntry("POST", "/api/test", "./src/api/test.ts"),
        createEntry("PUT", "/api/test", "./src/api/test.ts"),
        createEntry("DELETE", "/api/test", "./src/api/test.ts"),
        createEntry("PATCH", "/api/test", "./src/api/test.ts"),
      ];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain("GET as _api_test_GET");
      expect(code).toContain("POST as _api_test_POST");
      expect(code).toContain("PUT as _api_test_PUT");
      expect(code).toContain("DELETE as _api_test_DELETE");
      expect(code).toContain("PATCH as _api_test_PATCH");
    });

    it("should handle entries with different route structures", () => {
      const apiEntry = createEntry("GET", "/api", "./api/index.ts");
      const apiUsersEntry = createEntry(
        "GET",
        "/api/users",
        "./src/api/users.ts",
      );
      const nestedEntry = createEntry(
        "PUT",
        "/api/users/create",
        "./api/users/create.ts",
      );

      const entries = [apiEntry, apiUsersEntry, nestedEntry];

      const code = generateApiUtilsCode(entries);

      expect(code).toContain(
        'import { GET as _api_GET } from "' +
          apiEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain(
        'import { GET as _api_users_GET } from "' +
          apiUsersEntry.file.relativeToCwd() +
          '"',
      );
      expect(code).toContain(
        'import { PUT as _api_users_create_PUT } from "' +
          nestedEntry.file.relativeToCwd() +
          '"',
      );
    });
  });
});
