/**
 * Unit tests for src/core/code_generator.ts
 */
import { generateAssetUtilsCode } from "../../../src/assets/code_generation";
import { describe, it, expect } from "bun:test";

describe("generateAssetUtilsCode", () => {
  it("should generate code with a single asset", () => {
    const result = generateAssetUtilsCode(["/image.png"]);

    expect(result).toBe(
      '// Auto-generated by noxt\nexport type AssetId = "/image.png";\n',
    );
  });

  it("should generate code with multiple assets", () => {
    const result = generateAssetUtilsCode(["/image.png", "/style.css"]);

    expect(result).toContain('type AssetId = "/image.png" | "/style.css";');
  });
});
