/**
 * Unit tests for src/pwa/code_generation.ts
 */
import { generateServiceWorkerCode } from "../../../src/pwa/code_generation";
import { describe, it, expect } from "bun:test";

describe("generateServiceWorkerCode", () => {
  it("should generate service worker code with URLs from manifest", () => {
    const manifest = {
      "/": "index.html",
      "/about": "about/index.html",
      "/sw.js": "sw.js",
    };
    const result = generateServiceWorkerCode(manifest);

    expect(result).toContain("// Auto-generated by noxt — do not edit");
    expect(result).toMatch(/const CACHE_NAME = "noxt-[\d]+"/);
    expect(result).toContain('const PRECACHE_URLS = ["/","/about"];');
    // sw.js should be filtered out
    expect(result).not.toContain('"/sw.js"');
    expect(result).toContain("event.waitUntil");
    expect(result).toContain("caches.open");
    expect(result).toContain("self.addEventListener");
  });

  it("should handle empty manifest", () => {
    const result = generateServiceWorkerCode({});
    expect(result).toContain("const PRECACHE_URLS = [];");
  });

  it("should filter out sw.js files", () => {
    const manifest = {
      "/sw.js": "sw.js",
      "/nested/sw.js": "nested/sw.js",
    };
    const result = generateServiceWorkerCode(manifest);
    expect(result).not.toContain("/sw.js");
    expect(result).not.toContain("/nested/sw.js");
  });

  it("should include all non-sw.js URLs", () => {
    const manifest = {
      "/index.html": "index.html",
      "/styles.css": "styles.css",
      "/script.js": "script.js",
    };
    const result = generateServiceWorkerCode(manifest);
    expect(result).toContain(
      'const PRECACHE_URLS = ["/index.html","/styles.css","/script.js"];',
    );
  });
});
