/**
 * Copyright 2026 Luc BILLAUD
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 **/
import type { SSRRouteEntry } from "./types";
import type { HttpMethod } from "../core/types";

type SSRByFileMap = Map<
  string,
  {
    prefix: string;
    route: string;
    methods: Set<HttpMethod>;
  }
>;

function groupByRoute(entries: SSRRouteEntry<any>[]): SSRByFileMap {
  const importMap: SSRByFileMap = new Map();

  for (const entry of entries) {
    const importPrefix = entry.route.replaceAll(/[\\\/-]/g, "_");

    if (!importMap.has(entry.file.absolute)) {
      importMap.set(entry.file.absolute, {
        prefix: importPrefix,
        route: entry.route,
        methods: new Set<HttpMethod>(),
      });
    }
    importMap.get(entry.file.absolute)!.methods.add(entry.method);
  }

  return importMap;
}

function generateImportsCode(importMap: SSRByFileMap): string[] {
  const imports: string[] = [];

  for (const [fileToImport, importData] of importMap.entries()) {
    const importElements = importData.methods
      .values()
      .map((m) => `${m} as ${importData.prefix}_${m}`)
      .toArray();
    imports.push(
      `import { ${importElements.join(", ")} } from ${JSON.stringify(fileToImport)};`,
    );
  }

  return imports;
}

function generateRouterTypeCode(apiMap: SSRByFileMap): string {
  const routesData: string[] = [];

  for (const [_file, data] of apiMap.entries()) {
    const endpoints: string[] = [];
    for (const method of data.methods) {
      endpoints.push(`"${method}": ${data.prefix}_${method}`);
    }

    routesData.push(
      `"${data.route}": {
    ${endpoints.join(",\n    ")}
  }`,
    );
  }

  return `{
  ${routesData.join(",\n  ")}
}`;
}

export function generateSSRUtilsCode(
  entries: SSRRouteEntry<any>[],
  base?: string,
): string {
  const ssrMap = groupByRoute(entries);

  return `// Auto-generated by noxt
import { getSSRHandlers } from "noxt/runtime";
import type { InferDefinitions } from "noxt";
${generateImportsCode(ssrMap).join("\n")}

const ssrRoutesData = ${generateRouterTypeCode(ssrMap)} as const;
const handlers = getSSRHandlers(apiRoutesData, ${JSON.stringify(base ?? "")});

type SSRRoutes = InferDefinitions<typeof ssrRoutesData>;

export { type ApiRoutes, handlers };
`;
}
