import type { APIEndpointEntry } from "./build";
import type { HttpMethod } from "./types";

type ApiImportMap = Map<
  string,
  {
    prefix: string;
    methods: Set<HttpMethod>;
  }
>;
interface ApiRoute {
  route: string;
  method: HttpMethod;
  importedEntrypoint: string;
}

function entriesToImportsAndApiRoutes(entries: APIEndpointEntry<any, any>[]): {
  importMap: ApiImportMap;
  apiRoutes: ApiRoute[];
} {
  const importMap: ApiImportMap = new Map();
  const apiRoutes: ApiRoute[] = [];

  for (const entry of entries) {
    const importPrefix = entry.route.replaceAll(/\\\//, "_");

    importMap
      .getOrInsert(entry.file.relativeToCwd(), {
        prefix: importPrefix,
        methods: new Set<HttpMethod>(),
      })
      .methods.add(entry.method);

    apiRoutes.push({
      method: entry.method,
      route: entry.route,
      importedEntrypoint: `${importPrefix}_${entry.method}`,
    });
  }

  return {
    importMap,
    apiRoutes,
  };
}

function generateImportsCode(importMap: ApiImportMap): string[] {
  const imports: string[] = [];

  for (const [fileToImport, importData] of importMap.entries()) {
    const importElements = importData.methods
      .values()
      .map((m) => `${m} as ${importData.prefix}_${m}`)
      .toArray();
    imports.push(
      `import { ${importElements.join(", ")} } from ${fileToImport};`,
    );
  }

  return imports;
}

function generateRouterTypeCode(apiRoutes: ApiRoute[]): string {
  const routesData: string[] = [];

  for (const route of apiRoutes) {
    routesData.push(
      `"${route.method} ${route.route}": ${route.importedEntrypoint}`,
    );
  }

  return `{
${routesData.join(",\n\t")}
}`;
}

export function generateApiUtilsCode(
  entries: APIEndpointEntry<any, any>[],
  base?: string,
): string {
  const { importMap, apiRoutes } = entriesToImportsAndApiRoutes(entries);

  return `// Auto-generated by noxt
import { InferInput, InferOutput } from "valibot";
${generateImportsCode(importMap).join("\n")}

const apiRoutesData = ${generateRouterTypeCode(apiRoutes)};
type ApiRouter = typeof apiRoutesData;

const BASE = ${JSON.stringify(base ?? "")};
  
function api<TEndpoint extends keyof ApiRouter>(
  endpoint: TEndpoint,
): (
  input: v.InferOutput<ApiRouter[TEndpoint]['input']>,
) => Promise<v.InferInput<ApiRouter[TEndpoint]['output']>> {
  return async (input) => {
    let [method, url] = endpoint.split(' ', 2);
    url = BASE + url;
    const response = await fetch(url, { method });
    const data = await response.json();
    return data as v.InferInput<ApiRouter[TEndpoint]['output']>;
  };
}

export { link, type RouteId };
`;
}
