/**
 * Copyright 2026 Luc BILLAUD
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 **/
import type { APIEndpointEntry } from "./build";
import type { HttpMethod } from "./types";

type ApiImportMap = Map<
  string,
  {
    prefix: string;
    methods: Set<HttpMethod>;
  }
>;
interface ApiRoute {
  route: string;
  method: HttpMethod;
  importedEntrypoint: string;
}

function entriesToImportsAndApiRoutes(entries: APIEndpointEntry<any, any>[]): {
  importMap: ApiImportMap;
  apiRoutes: ApiRoute[];
} {
  const importMap: ApiImportMap = new Map();
  const apiRoutes: ApiRoute[] = [];

  for (const entry of entries) {
    const importPrefix = entry.route.replaceAll(/[\\\/-]/g, "_");

    importMap
      .getOrInsert(entry.file.absolute, {
        prefix: importPrefix,
        methods: new Set<HttpMethod>(),
      })
      .methods.add(entry.method);

    apiRoutes.push({
      method: entry.method,
      route: entry.route,
      importedEntrypoint: `${importPrefix}_${entry.method}`,
    });
  }

  return {
    importMap,
    apiRoutes,
  };
}

function generateImportsCode(importMap: ApiImportMap): string[] {
  const imports: string[] = [];

  for (const [fileToImport, importData] of importMap.entries()) {
    const importElements = importData.methods
      .values()
      .map((m) => `${m} as ${importData.prefix}_${m}`)
      .toArray();
    imports.push(
      `import { ${importElements.join(", ")} } from ${JSON.stringify(fileToImport)};`,
    );
  }

  return imports;
}

function generateRouterTypeCode(apiRoutes: ApiRoute[]): string {
  const routesData: string[] = [];

  for (const route of apiRoutes) {
    routesData.push(
      `"${route.method} ${route.route}": ${route.importedEntrypoint}`,
    );
  }

  return `{
${routesData.join(",\n\t")}
}`;
}

export function generateApiUtilsCode(
  entries: APIEndpointEntry<any, any>[],
  base?: string,
): string {
  const { importMap, apiRoutes } = entriesToImportsAndApiRoutes(entries);

  return `// Auto-generated by noxt
import { InferInput, InferOutput } from "valibot";
import { ApiRouter as NoxtApiRouter } from "noxt/runtime";
${generateImportsCode(importMap).join("\n")}

const apiRoutesData = ${generateRouterTypeCode(apiRoutes)};
const router = new NoxtApiRouter<typeof apiRoutesData>(${JSON.stringify(base ?? "")});

type ApiRouter = typeof router;

export { router, type ApiRouter };
`;
}
