/**
 * Unit tests for src/core/code_generator.ts
 */
import { generateLinkUtilsCode } from "../../../src/core/code_generation";
import { describe, it, expect } from "bun:test";

describe("generateLinkUtilsCode", () => {
  it("should generate code with a single route", () => {
    const result = generateLinkUtilsCode(["/"]);

    expect(result).toBe(
      '// Auto-generated by noxt\nexport type RouteId = "/";\n',
    );
  });

  it("should generate code with multiple routes", () => {
    const result = generateLinkUtilsCode(["/", "/about", "/contact"]);

    expect(result).toContain('type RouteId = "/" | "/about" | "/contact";');
  });

  it("should generate code with nested route paths", () => {
    const result = generateLinkUtilsCode(["/", "/blog/post"]);

    expect(result).toContain('type RouteId = "/" | "/blog/post";');
  });

  it("should handle routes with hyphens and underscores", () => {
    const result = generateLinkUtilsCode(["/about-us", "/my_profile"]);

    expect(result).toContain('type RouteId = "/about-us" | "/my_profile";');
  });

  it("should handle empty route list", () => {
    const result = generateLinkUtilsCode([]);

    expect(result).toContain("type RouteId = never;");
  });
});
