/**
 * Copyright 2026 Luc BILLAUD
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 **/

/**
 * Generates pure JavaScript code for the import map.
 *
 * This function creates template code that exports a prepareImportMap() function
 * which returns a mapping of route names to their HTML bundles.
 *
 * @param manifest - Record mapping route names to prerendered HTML file paths
 * @returns JavaScript code as a string
 */
export function generateLinkUtilsCode(routeNames: string[]): string {
  const routeIdType = routeNames.map((id) => JSON.stringify(id)).join(" | ");

  return `// Auto-generated by noxt
type RouteId = ${routeIdType};
type QueryParams = Record<string, string | number | boolean>;

function link(routeId: RouteId, query?: QueryParams): string {
  if (!query) return routeId;
  const entries = Object.entries(query);
  if (entries.length === 0) return routeId;
  const params = new URLSearchParams();
  for (const [k, v] of entries) {
    params.append(k, String(v));
  }
  return routeId + "?" + params.toString();
}

export { link, type RouteId };
`;
}

export function generateAssetUtilsCode(assetIds: string[]): string {
  const assetIdType = assetIds.map((id) => JSON.stringify(id)).join(" | ");

  return `// Auto-generated by noxt
type AssetId = ${assetIdType};

function asset(id: AssetId): string {
  return id;
}

export { asset, type AssetId };
`;
}
