import { describe, it, expect } from "bun:test";
import * as s from "superstruct";
import { Path } from "../../../src/core/fs";
import { generateSSRUtilsCode } from "../../../src/ssr/code_generation";
import type { SSRRouteEntry } from "../../../src/ssr/types";

function entry(
  method: string,
  route: string,
  filePath: string,
): SSRRouteEntry<any> {
  return {
    method: method as any,
    route,
    input: s.object({}),
    file: Path.fromRelative(filePath),
  };
}

describe("generateSSRUtilsCode", () => {
  it("generates the exact expected file for a single entry", () => {
    const e = entry("GET", "/hello", "ssr/hello.ts");

    const code = generateSSRUtilsCode([e]);

    expect(code).toBe(`// Auto-generated by noxt
import { getSSRHandlers } from "noxt/runtime";
import type { InferDefinitions } from "noxt";
import { GET as _hello_GET } from ${JSON.stringify(e.file.absolute)};

const ssrRoutesData = {
  "/hello": {
    "GET": _hello_GET
  }
} as const;
const handlers = getSSRHandlers(ssrRoutesData, "");

type SSRRoutes = InferDefinitions<typeof ssrRoutesData>;

export { type SSRRoutes, handlers };
`);
  });

  it("merges methods from the same file into one import", () => {
    const g = entry("GET", "/hello", "ssr/hello.ts");
    const p = entry("POST", "/hello", "ssr/hello.ts");

    const code = generateSSRUtilsCode([g, p]);

    expect(code).toBe(`// Auto-generated by noxt
import { getSSRHandlers } from "noxt/runtime";
import type { InferDefinitions } from "noxt";
import { GET as _hello_GET, POST as _hello_POST } from ${JSON.stringify(g.file.absolute)};

const ssrRoutesData = {
  "/hello": {
    "GET": _hello_GET,
    "POST": _hello_POST
  }
} as const;
const handlers = getSSRHandlers(ssrRoutesData, "");

type SSRRoutes = InferDefinitions<typeof ssrRoutesData>;

export { type SSRRoutes, handlers };
`);
  });

  it("passes base through to getSSRHandlers", () => {
    const e = entry("GET", "/a", "ssr/a.ts");

    const code = generateSSRUtilsCode([e], "/base");

    expect(code).toBe(`// Auto-generated by noxt
import { getSSRHandlers } from "noxt/runtime";
import type { InferDefinitions } from "noxt";
import { GET as _a_GET } from ${JSON.stringify(e.file.absolute)};

const ssrRoutesData = {
  "/a": {
    "GET": _a_GET
  }
} as const;
const handlers = getSSRHandlers(ssrRoutesData, "/base");

type SSRRoutes = InferDefinitions<typeof ssrRoutesData>;

export { type SSRRoutes, handlers };
`);
  });
});
